# Generated by Django 5.2.7 on 2025-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Número')),
                ('editora', models.CharField(choices=[('DC', 'DC Comics'), ('MARVEL', 'Marvel Comics'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Editora')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor / Roteirista')),
                ('data_lancamento', models.DateField(blank=True, null=True, verbose_name='Data de lançamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
    ]
